# Generated by Django 5.1.4 on 2024-12-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_de', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tille',
            new_name='title',
        ),
    ]
